name: Build
on: 
   workflow_dispatch:
jobs:
   build:
      name: Build & Upload Artifact
      runs-on: macOS-latest
      steps:
         - name: Build (i guess)
           run: |
              cd ${{ GITHUB.WORKSPACE }}
              make all
