name: Build
on: 
   workflow_dispatch:
jobs:
   build:
      name: Build & Upload Artifact
      runs-on: macOS-latest
      steps:
         - name: Build (i guess)
           run: |
              ROOTLESS = 1
              cd ${{ GITHUB.WORKSPACE }}
              make all --debug=v
              echo "Folder listing:"
              ls
