name: Build
on: 
   workflow_dispatch:
   push:
jobs:
   build:
      name: Build & Upload Artifact
      runs-on: macOS-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v4
         - name: Build (i guess)
           run: |
              ROOTLESS=1
              cd ${{ GITHUB.WORKSPACE }}
              make --debug=v
              echo "Folder listing:"
              ls
